---
title: "Analysis Summary - Go8"
author: "Rachel & Tina"
date: "`r Sys.Date()`"
format: 
  html:
    code-fold: false
---

```{r setup, include = FALSE}
library(tidyverse)
library(glue)
library(tidytext)
library(pluralize)
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      cache.path = "cache/",
                      fig.path = "images/",
                      message = FALSE,
                      warning = FALSE)
```

```{r}
choose <- function(x, name){
  df <- read_csv(x) %>% 
    mutate(School = name)
  
  if ("Outcomes" %in% colnames(df)){
    df <- df %>% 
    select(c("School","Course","Course_code", "Unit", "Unit_code", "Outcomes", "Overview"))
  } else {
    df <- df %>% 
    select(c("School","Course","Course_code", "Unit", "Unit_code", "Overview"))
  }
  df
}
```

```{r}
monash <- choose("data/monash-master-datasci.csv", "monash")
uom <- choose("data/uom-master-datasci.csv", "unimelb")
usyd <- choose("data/usyd-master-datasci.csv", "usyd")
uq <- choose("data/uq-master-datasci.csv","uq")
uade <- choose("data/uade-master-datasci.csv","uade")
anu <- choose("data/anu-master-appdatasci.csv", "anu") %>% 
  mutate(Course_code = as.character(Course_code))
unsw <- choose("data/unsw-master-datascidec.csv", "unsw")%>% 
   mutate(Course_code = as.character(Course_code))
uwa <- choose("data/uwa-master-datasci.csv","uwa") %>% 
  mutate(Course_code = as.character(Course_code))

#merge all data frames together
total <- bind_rows(monash, uom, usyd, uq, uade, anu, uwa, unsw)
```

## Text Analysis - Unit Overview

```{r category}
ai <- c("neural", "artificial", "machine")
it <- c("debugging", "software", "information", "data")
```

```{r overview data}
overview <- total %>%
  unnest_tokens(bigram, Overview, token = "ngrams", n = 2) %>% 
  separate(bigram,
           into = c("word1", "word2"),
           sep = " ") %>% 
  mutate(word1 = singularize(word1),
         word2 = singularize(word2)) %>% 
  mutate(word1 = ifelse(word1 == "datum","data", word1),
         word2 = ifelse(word2 == "datum","data", word2))

bigram_ov <- overview %>% 
  filter(!word1 %in% stop_words$word & !word2 %in% stop_words$word) %>%  
  filter(!word1 %in% c("content","topic", "unit", "subject", "final", "capstone", "involve", "project", "master", "practical", "programming") & 
         !word2 %in% c("student", "skill", "set", "piece", "concept", "capstone", "delivery", "domain", "manner", "due", "range", "unit", "master")) %>% 
  subset(!grepl("[0-9]", word1)) %>% 
  subset(!grepl("[0-9]", word2)) %>% 
  mutate(word = as_factor(paste(word1, word2, sep = " "))) %>%
  filter(!word == "data science") %>% 
  distinct(School, Unit, word) %>% 
  group_by(School) %>% 
  count(word, sort = TRUE) %>% 
  ungroup() %>% 
  mutate(category = case_when(str_detect(word, "data") ~ "IT",
                              str_detect(word, "regression") ~ "Math",
                              str_detect(word, "software") ~ "IT",
                              str_detect(word, "information") ~"IT",
                              str_detect(word, "neural") ~ "AI",
                              str_detect(word, "artificial") ~ "AI",
                              str_detect(word, "machine") ~ "AI",
                              str_detect(word, "debugging") ~ "IT")) %>% 
  mutate(category = if_else(is.na(category), "Other", category))
  
```

```{r}
bigram_ov %>% 
  filter(n > 3) %>% 
  mutate(word = fct_reorder(word, n, sum))%>% 
  ggplot(aes(x=n,
             y = word,
             fill = category))+
  geom_col()+
  scale_fill_brewer(palette = "Dark2") +
  theme_minimal()+
  labs(y = "",
       x = "",
       fill = "Category",
       title = "Bigram - unit overview (n > 3)")
```

```{r}
bigram_ov %>% 
  filter(n > 3) %>% 
  mutate(word = fct_reorder(word, n, sum))%>% 
  ggplot(aes(x=n,
             y = word,
             fill = category))+
  geom_col()+
  theme_minimal()+
  scale_fill_brewer(palette = "Dark2") +
  theme(legend.position = "bottom") +
  facet_wrap(~School, scales = "free_y") +
  scale_x_continuous(breaks = c(2,4,6,8,10)) +
  labs(y = "",
       x = "",
       fill = "Category",
       title = "Bigram - unit overview by univeristy (n > 3)")
```

## Text Analysis - Unit Learning Outcome

```{r}
outcome <- total %>%
  filter(!School == "unsw") %>% 
  unnest_tokens(bigram, Outcomes, token = "ngrams", n = 2) %>% 
  separate(bigram, 
           into = c("word1", "word2"),
           sep = " ") %>% 
  na.omit() %>% 
  mutate(word1 = singularize(word1),
         word2 = singularize(word2)) %>% 
  mutate(word1 = ifelse(word1 == "datum","data", word1),
         word2 = ifelse(word2 == "datum","data", word2))


bigram_oc <- outcome %>% 
  filter(!word1 %in% stop_words$word & !word2 %in% stop_words$word) %>%  
  filter(!word1 %in% c("student", "due", "basic") & 
         !word2 %in% c("student", "set", "completion", "knowledge", "setting", "understand", "effectively")) %>% 
  subset(!grepl("[0-9]", word1)) %>% 
  subset(!grepl("[0-9]", word2)) %>% 
  mutate(word = as_factor(paste(word1, word2, sep = " "))) %>%
  filter(!word == "data science") %>% 
  distinct(School, Unit, word) %>% 
  group_by(School) %>% 
  count(word, sort = TRUE) %>% 
  ungroup() %>% 
  mutate(category = case_when(str_detect(word, "statistical") ~ "Math",
                              str_detect(word, "research") ~"Research",
                              str_detect(word, "data") ~ "IT",
                              str_detect(word, "regression") ~ "Math",
                              str_detect(word, "software") ~ "IT",
                              str_detect(word, "information") ~"IT",
                              str_detect(word, "neural") ~ "AI",
                              str_detect(word, "artificial") ~ "AI",
                              str_detect(word, "machine") ~ "AI",
                              str_detect(word, "debugging") ~ "IT")) %>% 
   mutate(category = if_else(is.na(category), "Other", category))
  
```

```{r}
bigram_oc%>% 
  filter(n > 4) %>% 
  mutate(word = fct_reorder(word, n, sum))%>% 
  ggplot(aes(x=n,
             y = word,
             fill = category
             ))+
  geom_col()+
  scale_fill_brewer(palette = "Dark2") +
  theme_minimal()+
  labs(y = "",
       x = "",
       fill = "Category",
       title = "Bigram - unit outcome (n > 4)")
```


```{r}
bigram_oc%>% 
  filter(n > 4) %>% 
  mutate(word = fct_reorder(word, n, sum))%>% 
  ggplot(aes(x = n,
             y = word,
             fill = category))+
  geom_col()+
  scale_fill_brewer(palette = "Dark2") +
  theme_minimal()+
  theme(legend.position = "bottom") +
  facet_wrap(~School, scales = "free_y") +
  scale_x_continuous(breaks = c(0,3,6,9,12))+
  labs(y = "",
       x ="",
       fill = "Category",
       title = "Bigram - unit outcome by university (n > 4)")
```

## Component Analysis - Computational vs Statistical/Mathematical

```{r}
math <- c("STAT", "MATH", "MATHS", "STATS", "MAT", "MAST", "ACTL", "QBUS")

it <- c("COMP", "FIT", "CITS", "INFS", "COSC", "CSSE", "CSYS", "EDPC", "INMT", "PHIL", "PHYS", #it
        "BUSN","DATA", #data
        "INFO", "INFS") #analytics

commerce <- c("ECON", "FINS", "MARK", "ACCT", "FINM", "MGMT", "MKTG")

spatial <- c("GEOM", "ITLS")

science <- c("EDUC", "SCIE", 
             "SOCR") #social science

health <- c("BINF", "BMS", "HTIN", "PUBH")

comp <- total %>% 
  mutate(group = str_extract(Unit_code, "[A-Za-z]+")) %>% 
  group_by(School) %>% 
  count(group, sort = T) %>% 
  ungroup() %>% 
  mutate(category = case_when(group %in% it ~ "IT",
                              group %in% math ~ "Stat/Math",
                              group %in% commerce ~ "Commerce",
                              group %in% spatial ~ "Spatial",
                              group %in% science ~ "Science/Social Science",
                              group %in% health ~ "Health/Bioinfo/Biostat")) %>% 
  #Bioinformatics/Biostatistics
  mutate(category = if_else(is.na(category), "Other", category))
```

```{r}
comp %>% 
  mutate(category = fct_reorder(category, n, sum)) %>% 
  ggplot(aes(x = n,
             y = category,
             fill = category)) +
  geom_col() +
  scale_fill_brewer(palette = "Dark2") +
  labs(x = "",
       y = "",
       title = "Component analysis") +
  theme_minimal() +
  theme(legend.position = "bottom") 
```

```{r}
comp %>% 
  mutate(category = fct_reorder(category, n, sum)) %>% 
  ggplot(aes(x = n,
             y = category,
             fill = category)) +
  geom_col() +
  scale_fill_brewer(palette = "Dark2") +
  labs(x = "",
       y = "",
       title = "Component analysis by univeristy") +
  facet_wrap(~School, scales = "free_y") +
  theme_minimal() +
  theme(legend.position = "bottom")
  
```

## word to vec

```{r}
library(stringr)
library(SnowballC)

total <- total %>% 
  mutate(description = if_else(School == "unsw", 
                               total$Overview, 
                               str_c(total$Overview, " ", total$Outcomes)))

words <- total %>% 
  unnest_tokens(words, description) %>% 
  filter(!words %in% stop_words$word) %>% 
  subset(!grepl("[0-9]", words)) %>% 
  mutate(stem = wordStem(words, language = "english"))
```

```{r}
target::tar_load(lda_model10_s)
target::tar_load(lda_model12_ssc)

topics_ssc <- tidy(lda_model12_ssc, matrix = "beta")

topics_s <- tidy(lda_model10_s, matrix = "beta")

```



```{r}
words_ssc <- words %>% 
  left_join(topics_ssc, by = c("stem" = "term") ) %>% 
  group_by(School, Course, Course_code, Unit, Unit_code, words, stem) %>% 
  top_n(1, beta) %>% 
  mutate(topic = as_factor(topic))

words_s <- words %>% 
  left_join(topics_s, by = c("stem" = "term") ) %>% 
  group_by(School, Course, Course_code, Unit, Unit_code, words, stem) %>% 
  top_n(1, beta) %>% 
  mutate(topic = as_factor(topic))
```


```{r}
words_ssc %>% 
  distinct(School, Unit, topic) %>% 
  group_by(School) %>% 
  count(topic, sort = TRUE) %>% 
  ungroup() %>% 
  mutate(topic = fct_reorder(topic, n, sum))%>% #reorder_within(topic, n, School)
  ggplot(aes(x = n,
             y = topic,
             fill = topic))+
  geom_col() +
  scale_fill_brewer(palette = "Paired") +
  theme_minimal() +
  #scale_y_reordered() +
  facet_wrap(~School, scales = "free_y") +
  theme(legend.position = "none") +
  labs(title = "Topic Count - LDA_SSC")
```

```{r}
topicmodels::get_terms(targets::tar_read(lda_model12_ssc), k = 10)
```

```{r}
words_s %>% 
  distinct(School, Unit, topic) %>% 
  group_by(School) %>% 
  count(topic, sort = TRUE) %>% 
  ungroup() %>% 
  mutate(topic = fct_reorder(topic, n, sum))%>% #reorder_within(topic, n, School)
  ggplot(aes(x = n,
             y = topic,
             fill = topic)) +
  geom_col() +
  scale_fill_brewer(palette = "Paired") +
  theme_minimal() +
  #scale_y_reordered() +
  facet_wrap(~School, scales = "free_y") +
  theme(legend.position = "none") +
  labs(title = "Topic Count - LDA_S")

```

```{r}
topicmodels::get_terms(targets::tar_read(lda_model10_s), k = 10)
```

