---
title: "Master of Data Science - La Trobe University"
author: "Rachel Xinrui WANG"
date: "`r Sys.Date()`"
format: 
  html:
    code-fold: false
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(RSelenium)
library(glue)
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      cache.path = "cache/",
                      fig.path = "images/")

```

```{r}
# remDr$close()
# system("taskkill /im java.exe /f", intern=FALSE, ignore.stdout=FALSE)
rD <- rsDriver(browser="firefox", port=4778L, verbose=F)
remDr <- rD[["client"]]

baseurl <- "https://handbook.latrobe.edu.au"

wait_time <- function() Sys.sleep(sample(2:3, 1))

data <- tibble(Course = character(),
               Course_code = character(),
               Course_overview = character(),
               Unit = character(),
               Unit_code = character(),
               Overview = character(),
               RequesiteRules = character(),
               #Prerequisite = character(),
               #Corequisite = character(),
               #Prohibition = character(),
               LearningOutcome = character())

remDr$navigate("https://handbook.latrobe.edu.au/courses/2022/SMDS")
course_html <- read_html(remDr$getPageSource()[[1]])

```


```{r}
tryCatch({
    
    # extract name of the course
    title <- course_html %>% 
      html_element("h2") %>% 
      html_text()
    
    # extract course code
    code <- course_html %>% 
      html_element("h5") %>% 
      html_text()
    
    # extract course overview
    coverview <- course_html %>% 
      html_element("#Overview") %>% 
      html_element(".css-1x8hb4i-Box-CardBody") %>% 
      html_elements("div") %>% 
      .[!is.na(html_attr(., "aria-hidden")) & 
          html_attr(., "aria-hidden")=="true"] %>% 
      html_text()
    
    # get all core and elective units for the course
    links <- course_html %>% 
      html_element("#curriculumStructure") %>% 
      html_element(".css-to4w00-Box") %>% 
      html_elements("a") %>% 
      html_attr("href") %>% 
      as_tibble() %>% 
      filter(nchar(value) < 25)
    
    curriculum <- as.vector(links$value)
  
    for(unit in curriculum) {
      remDr$navigate(glue("{baseurl}{unit}"))
      wait_time()
      unit_html <- read_html(remDr$getPageSource()[[1]])
      
      # get unit name
      subject_text <- unit_html %>% 
        html_element("h2") %>% 
        html_text()
      
      # get unit code
      cunit <- unit_html %>% 
        html_element("h5") %>% 
        html_text()
      
      # unit overview
      overview <- unit_html %>% 
        html_element("#Overview") %>% 
        html_element(".css-1x8hb4i-Box-CardBody") %>% 
        html_elements("div") %>% 
        .[!is.na(html_attr(., "aria-hidden")) & 
          html_attr(., "aria-hidden")=="true"] %>% 
        html_text()
      
      # unit learning outcome
      lo <- unit_html %>% 
        html_element("#Subjectintendedlearningoutcomes") %>% 
        html_elements(".AccordionItem") %>% 
        html_text() %>% 
        str_remove(".remove")
      
      
      
      # check if there's any requisite, extract if yes, otherwise take the requisite rules
      reqs <- unit_html %>% 
        html_element("#requisites")
      
      reqs_list <- list()
      pre <- "None"
      
      if(length(reqs) > 0) {
        reqs <- reqs %>% 
          html_element(".css-to4w00-Box") %>% 
          html_children()
         
      } else{
        reqrules <- unit_html %>% 
          html_element("#Requisiterules")
        
         if(length(reqrules) > 0) {
            pre <- unit_html %>% 
              html_element("#Requisiterules") %>% 
              html_element(".css-1l0t84s-Box-CardBody") %>% 
              html_text() %>%
              trimws()
      } 
        
      }
      
      for(areq in reqs) {
        area <- areq %>% 
          html_element("strong") %>% 
          html_text()
        
        reqs_list[[area]] <- areq %>% 
          html_elements(".unit-title") %>% 
          html_text() %>% 
          paste0(collapse = ", ")
      }
      
      data <- data %>% 
        bind_rows(tibble(!!!c(list(Course = title, 
                                   Course_code = code, 
                                   Course_overview = coverview,
                                   Unit_code = cunit,
                                   Unit = subject_text,
                                   Overview = overview,
                                   LearningOutcome = paste0(lo, collapse = " "),
                                   RequesiteRules = pre
                                   ),
                              reqs_list))) %>% 
        mutate(Unit_type = 
                 case_when(row_number()<= 7 ~ "Core",
                           row_number() > 7 & row_number() < 17 ~ "Core choice pathway",
                           row_number() >= 17 & row_number() < 19 ~ "Elective",
                           row_number() > 19 ~ "Specialisation"))
    }

    }
    , error = function(x) x
    )

```


```{r}
# 51 out of 53 units scraped
write.csv(data, file = "data/latrobe-master-datasci.csv")

```

