---
title: " Monash Master of Business Analytics"
author: "Emi Tanaka"
date: "`r Sys.Date()`"
format: 
  html: 
    code-fold: false
---


```{r setup, include = FALSE}
library(tidyverse)
library(visNetwork)
library(rvest)
library(RSelenium)
library(glue)
library(tidytext)
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      cache.path = "cache/",
                      fig.path = "images/")

```


```{r monash-ba}
rD <- rsDriver(browser="firefox", port=4790L, verbose=F)
remDr <- rD[["client"]]

code <- "B6022"
baseurl <- "https://handbook.monash.edu"
year <- 2022
wait_time <- function() Sys.sleep(sample(3:5, 1))

remDr$navigate(glue("{baseurl}/2022/courses/{code}?year=2022"))
course_html <- read_html(remDr$getPageSource()[[1]])

title <- course_html %>% 
  html_element("h2") %>% 
  html_text() %>% 
  str_replace(paste0(code, " - "), "")

curriculum <- course_html %>% 
  html_element("#curriculumStructure") %>% 
  html_element(".css-to4w00-Box") %>% 
  html_elements("a") %>% 
  html_attr("href")

data <- map_dfr(curriculum, function(unit) {
      cunit <- str_replace(unit, paste0("/", year, "/units/"), "")
      remDr$navigate(glue("{baseurl}{unit}"))
      wait_time()
      unit_html <- read_html(remDr$getPageSource()[[1]])
      subject_text <- unit_html %>% 
        html_element("h2") %>% 
        html_text() 
    
      reqs <- unit_html %>% 
        html_element("#requisites") 
      
      if(length(reqs)) {
        reqs <- reqs %>% 
          html_element(".css-to4w00-Box") %>% 
          html_children()
      }
      
      reqs_list <- list()
      for(areq in reqs) {
        area <- areq %>% 
          html_element("strong") %>% 
          html_text()
        reqs_list[[area]] <- areq %>% 
          html_elements("a") %>% 
          html_attr("href") %>% 
          list()
      }
      
      overviews <- unit_html %>% 
        html_element("#Overview") %>% 
        html_element(".OverviewInner") %>% 
        html_elements("div") %>% 
        html_text() %>% 
        pluck(2)
      
      outcomes <- unit_html %>% 
        html_elements("#Learningoutcomes .AccordionItem") %>%
        html_text() %>% 
        str_replace("^[0-9]+[.]", "") %>%
        str_replace("keyboard_arrow_down$", "")
      message(glue::glue("{cunit} done!"))
      tibble(!!!c(list(Course = title, 
                       Course_code = code, 
                       Unit_code = cunit,
                       Unit = subject_text,
                       Overview = overviews,
                       Outcomes = list(outcomes)), 
                       reqs_list))
})

data %>% 
  rowwise() %>% 
  mutate(Outcomes = paste(Outcomes, collapse = "| "),
         Prohibition = paste(Prohibition, collapse = ", "),
         Prerequisite = paste(Prerequisite, collapse = ", "),
         Corequisite = NA) %>% 
  mutate(across(c(Prohibition, Prerequisite, Corequisite), 
               ~ifelse(is.na(.x), 
                       "", 
                       str_replace_all(.x, glue::glue("/{year}/units/"), "")))) %>% 
  write_csv(file = "data/monash-master-businessanalytics.csv")
```

