---
title: "Exploratory Text Analysis of G8 Schools' Unit Overviews (Master Degrees)"
author: "Tina Tsou"
date: "`r Sys.Date()`"
format: 
  html: 
    code-fold: false
---


```{r setup, include = FALSE}
library(tidyverse)
library(glue)
library(tidytext)
library(pluralize)
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      cache.path = "cache/",
                      fig.path = "images/")

```

```{r datasets}
choose <- function(x, name){
  read.csv(x) %>% 
    mutate(School = name) %>% 
    select(c("School","Course","Course_code", "Unit", "Unit_code", "Overview"))
}

monash1 <- choose("data/monash-master-businessanalytics.csv", "monash")
monash2 <- choose("data/monash-master-datasci.csv", "monash")
monash3 <- choose("data/monash-master-healthanalytics.csv", "monash")
melu <- choose("data/uom-master-datasci.csv", "uofmel")
usyd <- choose("data/usyd-master-datasci.csv", "usyd")
uq <- choose("data/uq-master-datasci.csv","uq")
uade <- choose("data/uade-master-datasci.csv","uade")
anu <- choose("data/anu-master-appdatasci.csv", "anu") %>% 
  mutate(Course_code = as.character(Course_code))
unsw <- choose("data/unsw-master-datascidec.csv", "unsw")%>% 
  mutate(Course_code = as.character(Course_code))
uwa <- choose("data/uwa-master-datasci.csv","uwa") %>% 
  mutate(Course_code = as.character(Course_code))


#merge all data frames together
total <- bind_rows(monash1, melu, usyd, uq, uade, anu, unsw, uwa)

```


```{r overview data}
unnested <- total %>%
  group_by(School) %>% 
  unnest_tokens(word, Overview) %>% 
  anti_join(stop_words,by = "word") %>% 
  mutate(word = singularize(word)) %>% 
  mutate(word= ifelse(word == "datum","data", word))

school_words<- unnested %>% 
  subset(!grepl("[0-9]", word)) %>% #remove words with numbers
  count(word, sort = TRUE) 
  
```

```{r}
school_words %>% 
  filter(n >20) %>% 
#  mutate(word = fct_reorder(word, n))%>% 
  ggplot(aes(x=n,
             y = reorder(word, n)))+
  geom_col()+
  theme_minimal()
```

```{r bigram data}
bigram <- total %>%
#  group_by(School) %>% 
  unnest_tokens(bigram, Overview, token = "ngrams",n=2) %>% 
  separate(bigram, c("word1", "word2") , sep = " ") %>% 
  filter(!word1 %in% stop_words$word & !word2 %in% stop_words$word ) %>% 
  mutate(bigram = paste(word1, word2)) 

# school_words<- unnested %>% 
#   subset(!grepl("[0-9]", word)) %>% #remove words with numbers
#   count(word, sort = TRUE) 

bigram_counts <- bigram %>%
  group_by(School,Unit_code) %>% 
  distinct(bigram) %>% 
  ungroup() %>% 
  group_by(School) %>% 
  count(bigram, sort = TRUE)

bigram_counts %>%
  filter(n>1) %>% 
  group_by(School) %>% 
  slice_max(order_by = n, n = 10) %>% 
  ggplot(aes(y = bigram, x = n))+
  geom_col()+
  facet_wrap(.~School, scales = "free")
```


```{r trigram}
trigram <- total %>%
#  group_by(School) %>% 
  unnest_tokens(trigram, Overview, token = "ngrams",n=3) %>% 
  separate(trigram, c("word1", "word2", "word3") , sep = " ") %>% 
  filter(!word1 %in% stop_words$word & !word2 %in% stop_words$word  & !word3 %in% stop_words$word ) %>% 
  mutate(trigram = paste(word1, word2, word3)) 

# school_words<- unnested %>% 
#   subset(!grepl("[0-9]", word)) %>% #remove words with numbers
#   count(word, sort = TRUE) 

trigram_counts <- trigram %>%
  group_by(School,Unit_code) %>% 
  distinct(trigram) %>% 
  ungroup() %>% 
  group_by(School) %>% 
  count(trigram, sort = TRUE)

trigram_counts %>%
  filter(n>1) %>% 
  group_by(School) %>% 
  slice_max(order_by = n, n = 10) %>% 
  ggplot(aes(y = trigram, x = n))+
  geom_col()+
  facet_wrap(.~School, scales = "free_y")
```

```{r}

#str_detect(text, “ r[.,; ]")
#str_detect(text, “ python[.,; ]")
#str_detect(text, “ julia[.,; ]")
#matlab, stata, spss, sas
```


```{r stem words}
library(SnowballC)
stemword <- total %>%
  group_by(School, Unit) %>%
  unnest_tokens(word, Overview) %>%
  anti_join(stop_words,by = "word") %>% 
  distinct(School, Unit, word) %>% 
  ungroup() %>% 
  group_by(School) %>% 
  mutate(stem = wordStem(word)) %>%
  count(stem, sort = TRUE)


stemword %>% 
  filter(n > 10) %>% 
  ggplot(aes(n, fct_reorder(stem, n))) +
  geom_col() +
  labs(y = NULL) +
  facet_wrap(~School, scales = "free_y")
```

```{r hunspell_stem}
library(hunspell)

stemword2 <- total %>%
  group_by(School, Unit) %>%
  unnest_tokens(word, Overview) %>%
  anti_join(stop_words,by = "word") %>% 
  distinct(School, Unit, word) %>% 
  ungroup() %>% 
  group_by(School) %>% 
  mutate(stem = hunspell_stem(word)) %>%
  rowwise() %>% 
  mutate(stem = paste(stem, collapse = ','))
#  unnest(stem) %>%
#  count(stem, sort = TRUE)


stemword2 %>% 
  filter(n > 10) %>% 
  ggplot(aes(n, fct_reorder(stem, n))) +
  geom_col() +
  labs(y = NULL) +
  facet_wrap(~School, scales = "free_y")
```


