---
title: "Text Analysis - Unit Outcome (Group of 8)"
author: "Rachel Xinrui WANG"
date: "`r Sys.Date()`"
format: 
  html:
    code-fold: false
---

```{r setup, include = FALSE}
library(tidyverse)
library(tidytext)
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      cache.path = "cache/",
                      fig.path = "images/")

```

```{r combine data}
# uom <- read_csv("data/uom-master-datasci.csv")
# monash <- read_csv("data/monash-master-datasci.csv")
# anu <- read_csv("data/anu-master-appdatasci.csv")
# uade <- read_csv("data/uade-master-datasci.csv")
# unsw <- read_csv("data/unsw-master-datascidec.csv")
# uq <- read_csv("data/uq-master-datasci.csv")
# usyd <- read_csv("data/usyd-master-datasci.csv")
# uwa <- read_csv("data/uwa-master-datasci.csv")
```

```{r}
choose <- function(x, name){
  read_csv(x) %>% 
    mutate(School = name) %>% 
    select(c("School","Course","Course_code", "Unit", "Unit_code", "Outcomes"))
}
```

```{r}
#monash_ba <- choose("data/monash-master-businessanalytics.csv", "monash_ba")
monash <- choose("data/monash-master-datasci.csv", "monash_ds")
#monash_ha <- choose("data/monash-master-healthanalytics.csv", "monash_ha")
uom <- choose("data/uom-master-datasci.csv", "unimelb")
usyd <- choose("data/usyd-master-datasci.csv", "usyd")
uq <- choose("data/uq-master-datasci.csv","uq")
uade <- choose("data/uade-master-datasci.csv","uade")
anu <- choose("data/anu-master-appdatasci.csv", "anu") %>% 
  mutate(Course_code = as.character(Course_code))
# unsw <- choose("data/unsw-master-datascidec.csv", "unsw")%>% 
#   mutate(Course_code = as.character(Course_code))
uwa <- choose("data/uwa-master-datasci.csv","uwa") %>% 
  mutate(Course_code = as.character(Course_code))


#merge all data frames together
total <- bind_rows(monash, uom, usyd, uq, uade, anu, uwa)
```

```{r}
text <- total %>% 
  unnest_tokens(bigram, Outcomes, token = "ngrams", n = 2) %>% 
  separate(bigram, 
           into = c("word1", "word2"),
           sep = " ") %>% 
  filter(!(word1 %in% stop_words$word | word2 %in% stop_words$word)) %>% 
  subset(!grepl("[0-9]", word1)) %>% 
  subset(!grepl("[0-9]", word2)) %>% 
  mutate(word = paste(word1, word2, sep = " ")) %>% 
  group_by(School) %>% 
  count(word, sort = TRUE) %>% 
  ungroup()
```

```{r}
text %>% 
  filter(n > 4) %>% 
  ggplot(aes(n, fct_reorder(word, n))) +
  geom_col() +
  labs(y = NULL)
```

```{r}
text %>% 
  filter(n > 4) %>% 
  ggplot(aes(n, fct_reorder(word, n))) +
  geom_col() +
  labs(y = NULL) +
  facet_wrap(~School, scales = "free_y")
```


