---
title: "Business of Applied Data Science - University of Adelaide"
author: "Tina Tsou"
date: "`r Sys.Date()`"
format: 
  html: 
    code-fold: false
---


```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(RSelenium)
library(seleniumPipes)
library(glue)
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      cache.path = "cache/",
                      fig.path = "images/")

```

```{r adelaide}
rD <- rsDriver(browser="firefox", port=4779L, verbose=F)
remDr <- rD[["client"]]
```


```{r adelaide}
baseurl<- "https://calendar.adelaide.edu.au/aprcw/2022/bapda_bappda"
wait_time <- function() Sys.sleep(sample(3:5, 1))

data <- tibble(Course = character(),
               Course_code = character(),
               Unit = character(),
               Unit_code = character(),
               Overview = character(),
               LearningOutcome = character(),
               Prohibition = character(),
               Prerequisite = character(),
               Corequisite = character())
  
tryCatch({
  remDr$navigate(glue("{baseurl}"))
  wait_time()
  course_html <- read_html(remDr$getPageSource()[[1]])
  
    title <- course_html %>% 
        html_element("#page-title") %>% 
        html_text() %>% 
        str_trim()

    course_code <- course_html %>% 
          html_element("div.span4:nth-child(1)") %>% 
          html_element(" p:nth-child(2)") %>% 
          html_text()
    
      corecourses <-course_html %>% 
      html_element("#tab-corecourses") %>% 
      html_element("fieldset:nth-child(3)") %>% 
      html_element("div:nth-child(2)") %>% 
      html_elements("table") %>% 
      html_element("tbody") %>% 
      html_children() %>% 
      html_element("a") %>% 
      html_attr("href")%>% as_tibble()
      
      majors <- course_html %>% 
       html_element("#tab-major") %>% 
      html_elements("fieldset") %>% 
      html_element("div:nth-child(2)") %>% 
      html_elements("table") %>% 
      html_elements("tbody:nth-child(2)") %>% 
      html_children() %>% 
      html_element("a") %>% 
       html_attr("href")%>% as_tibble()
    
    electives <- course_html %>% 
       html_element("#tab-electives") %>% 
      html_elements("fieldset") %>% 
      html_element("div:nth-child(2)") %>% 
      html_elements("table") %>% 
      html_element("tbody:nth-child(2)") %>% 
      html_children() %>% 
      html_element("a") %>% 
      html_attr("href")%>% as_tibble() 
    
      curriculum <- rbind(corecourses, majors) %>% rbind(electives) %>% 
        remove_missing()

    for(i in 1:nrow(curriculum)) {
      unit <- curriculum[i,]
      remDr$navigate(glue("https:{unit}"))
      wait_time()
      webElem<- remDr$findElement(
        using = "css",
                "html body div.keyline table tbody tr td div.content p table tbody tr td.odd a")
      webElem$clickElement()
      wait_time()
      webElem2<- remDr$findElement(
        using = "xpath",
                "/html/body/div[1]/table[4]/tbody/tr/td/div/a[2]")
      webElem2$clickElement()
      wait_time()
      unit_html <- read_html(remDr$getPageSource()[[1]])
      
      ## get the course name and course number of each course
      unitinfo <- unit_html %>% 
        html_element("li.accordion-item:nth-child(1)") %>% 
        html_element("div:nth-child(2)") %>% 
        html_element("div:nth-child(2)") %>% 
        html_table()
      
      unitname <- unitinfo %>% 
                    filter(X1 == 'Course') %>% 
                    select(X2) %>% 
                    as.character()
      
      unitcode <- unitinfo %>% 
                    filter(X1 == 'Course Code') %>% 
                    select(X2) %>% 
                    as.character()

      #message(paste("Going through the unit:", cunit[,2]))
      
      ## get the overview of the unit
      overview <- unitinfo %>% 
                    filter(X1 == 'Course Description') %>% 
                    select(X2) %>% 
                    as.character()
      
      
      ## prerequisite 
       if('Prerequisites' %in% unitinfo$X1){
                pre <- unitinfo %>% 
                  filter(X1 == 'Prerequisites') %>% 
                  select(X2) %>% 
                  as.character()}else{pre <- NA}
       
       ## prohibition
       if('Incompatible' %in% unitinfo$X1){
                 pro <-  unitinfo %>% 
                    filter(X1 == 'Incompatible') %>% 
                    select(X2) %>% 
                    as.character()}else{pro <- NA}
       ## Corequisite
       if('Corequisite' %in% unitinfo$X1){
                co <-unitinfo %>% 
                  filter(X1 == 'Corequisite') %>% 
                  select(X2) %>% 
                  as.character()}else{co <-NA}

      webElem3<- remDr$findElement( using = "xpath",
                                    "//*[@id='2-learning-outcomes']")
      webElem3$clickElement()
      wait_time()
      unit_html <-  read_html(remDr$getPageSource()[[1]])
        ##learning outcomes
       if(unitcode=="COMP SCI 7318"){
         lc <- unit_html %>% 
            html_element("li.accordion-item:nth-child(2)") %>% 
            html_element("div:nth-child(2)") %>%
            html_element("div:nth-child(2)") %>% 
            html_element("div:nth-child(1)") %>% 
           html_text()%>%
           str_remove_all("\n        ") 
         test <- 0
       }else if(unitcode =="COMMGMT 7023OL"){
         test <- list()
       }else{test <- unit_html %>% 
          html_element(".ui-accordion-content-active") %>% 
          html_element("div:nth-child(2)")}
      
      if(length(test) > 0) {
        if(unitcode =="COMMGMT 7023OL"){
          lc <- unit_html %>% 
          html_element("#page-content") %>% 
          html_element("div.detail-data") %>% 
          html_element("div.ui-accordion-wrapper") %>% 
          html_element("li:nth-child(2)") %>% 
          html_element("div") %>% 
          html_element("div") %>% 
          html_element("table:nth-child(2)") %>% 
          html_element("tbody") %>% 
          html_children() %>% 
          html_element("td:nth-child(2)") %>% 
          html_text() %>%  str_remove_all("\n") %>% 
          paste(collapse = " ")
        }else{
          lc <- unit_html %>% 
          html_element(".ui-accordion-content-active") %>% 
          html_element("div:nth-child(2)") %>% 
          html_element("div:nth-child(1)") %>% 
          html_text() %>% str_remove_all("\n        ") 
        }
      }else {
        lc <- NA
      }
      
      data <- data %>% 
        bind_rows(tibble(!!!list(Course = title, 
                                   Course_code = course_code, 
                                   Unit = unitname,
                                   Unit_code = unitcode,
                                   Overview = overview,
                                   LearningOutcome =lc,
                                  Prohibition = pro,
                                  Prerequisite= pre,
                                 Corequisite = co))) 
      }
      
    },error = function(x) x)
  

write.csv(data, file = "data/uade-master-datasci.csv")
# stop the rselenium server
#rD[["server"]]$stop()
```
