---
title: "Master of Data Science and Decisions - UNSW"
author: "Rachel Xinrui WANG"
date: "`r Sys.Date()`"
format: 
  html:
    code-fold: false
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(RSelenium)
library(glue)
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      cache.path = "cache/",
                      fig.path = "images/")

```

```{r}
# html <- read_html("https://www.unsw.edu.au/study/postgraduate/master-of-data-science-and-decisions?studentType=Domestic")

#html %>%
#  html_text() %>% 
#  cat()
```


```{r}
# system("taskkill /im java.exe /f", intern=FALSE, ignore.stdout=FALSE)
rD <- rsDriver(browser="firefox", port=4778L, verbose=F)
remDr <- rD[["client"]]

baseurl <- "https://www.handbook.unsw.edu.au"
year <- 2022
wait_time <- function() Sys.sleep(sample(3:5, 1))

data <- tibble(Course = character(),
               Course_code = character(),
               Course_overview = character(),
               Unit = character(),
               Unit_code = character(),
               Overview = character(),
               Prohibition = character(),
               Prerequisite = character())

remDr$navigate("https://www.handbook.unsw.edu.au/postgraduate/programs/2022/8959")
course_html <- read_html(remDr$getPageSource()[[1]])

```

```{r}
tryCatch({
    
    # extract name of the course
    title <- course_html %>% 
      html_element("h2") %>% 
      html_text()
    
    # extract course overview
    coverview <- course_html %>% 
      html_element("#Overview") %>% 
      html_element(".css-1x8hb4i-Box-CardBody") %>% 
      html_elements("div") %>% 
      .[!is.na(html_attr(., "aria-hidden")) & 
          html_attr(., "aria-hidden")=="true"] %>% 
      html_text()
    
    # get all links and separate into specilisation and core units
    links <- course_html %>% 
      html_element("#curriculumStructure") %>% 
      html_element(".css-to4w00-Box") %>% 
      #html_element(".cmp-text") %>% 
      html_elements("div") %>%
      html_elements("a") %>% 
      html_attr("href")
    
    specialisation <- links[1:4]
    
    core <- links[5:length(links)]
    
    # Extract core and elective units for each specialisation
    
    for(spec in specialisation){
      remDr$navigate(glue("{baseurl}{spec}"))
      wait_time()
      spec_html <- read_html(remDr$getPageSource()[[1]])
      
      spec_core <- spec_html %>% 
        html_element("#SpecialisationStructure") %>% 
        html_element("")
    }
    
  
    for(unit in curriculum) {
      remDr$navigate(glue("{baseurl}{unit}"))
      wait_time()
      unit_html <- read_html(remDr$getPageSource()[[1]])
      
      # get unit name
      subject_text <- unit_html %>% 
        html_element("h2") %>% 
        html_text()
      
      # get unit code
      cunit <- unit_html %>% 
        html_element("h5") %>% 
        html_text()
      
      # unit overview
      overviews <- unit_html %>% 
        html_element("#Overview") %>% 
        html_element(".css-1x8hb4i-Box-CardBody") %>% 
        html_elements("div") %>% 
        .[!is.na(html_attr(., "aria-hidden")) & 
            html_attr(., "aria-hidden")=="true"] %>% 
        html_text()
      
      # check if there's any pre-requisites and extract if yes
      reqs <- unit_html %>% 
        html_element("#ConditionsforEnrolment")
      
      if(length(reqs) > 0) {
        pre <- unit_html %>% 
        html_element("#ConditionsforEnrolment") %>% 
        html_elements(".css-1x8hb4i-Box-CardBody") %>% 
        html_text() 
      } else {
        pre <- "None"
      }
      
      # check if there's any prohibations and extract if yes
      probs <- unit_html %>% 
        html_element("#ExclusionCourses")
      
      if(length(probs) > 0) {
        pro <- unit_html %>% 
        html_element("#ExclusionCourses") %>% 
        html_elements(".unit-title") %>% 
        html_text() 
      } else {
        pro <- "None"
      }
      
      
      data_core <- data %>% 
        bind_rows(tibble(!!!c(list(Course = paste0("Master of ", title), 
                                   Course_code = "8959", 
                                   Course_overview = coverview,
                                   Unit_code = cunit,
                                   Unit = subject_text,
                                   Overview = overviews,
                                   Prerequisite = pre,
                                   Prohibition = pro
                                   )))) %>% 
        mutate(Unit_type = ut)
    }
    
    

    }
    , error = function(x) x
    )

```

```{r}
write.csv(data, file = "data/unsw-master-datascidec.csv")
```

