---
title: " RMIT Master of Data Science"
author: "Tina"
date: "`r Sys.Date()`"
format: 
  html: 
    code-fold: false
---


```{r setup, include = FALSE}
library(tidyverse)
library(visNetwork)
library(rvest)
library(RSelenium)
library(glue)
library(tidytext)
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      cache.path = "cache/",
                      fig.path = "images/")

```


```{r RMIT}
rD <- rsDriver(browser="firefox", port=4790L, verbose=F)
remDr <- rD[["client"]]

wait_time <- function() Sys.sleep(sample(3:5, 1))

remDr$navigate("https://www.rmit.edu.au/study-with-us/levels-of-study/postgraduate-study/masters-by-coursework/master-of-data-science-mc267/mc267auscy")
course_html <- read_html(remDr$getPageSource()[[1]])

title <- course_html %>% 
  html_element("h1") %>% 
  html_text()

curric <- course_html %>% 
  html_elements(xpath = "//div[@class='requirementRequirementHTML table-responsive']") %>%
  html_elements(xpath = "//table[@class = 'courseTable scrollable-table']") %>% 
  html_elements(xpath = "//tr[@class = 'courseLine']") %>% 
  html_elements("a") %>% 
  html_attr("href")

curric2 <- course_html %>% 
  html_elements(xpath = "//div[@class='requirementRequirementHTML table-responsive']") %>%
  html_elements(xpath = "//table[@class = 'courseTable scrollable-table']") %>% 
  html_elements(xpath = "//tr[@class = 'lastCourseLine']") %>% 
  html_elements("a") %>% 
  html_attr("href")

curriculum<- append(curric, curric2)

data <- map_dfr(curriculum, function(unit) {
      remDr$navigate(unit)
      wait_time()
      unit_html <- read_html(remDr$getPageSource()[[1]])
      cunit <- unit_html %>% 
        html_element("#contentpadding") %>% 
        html_element("table") %>% 
        html_element("tr:nth-child(2)") %>% 
        html_element("p") %>% 
        html_text()
      
      subject_text <- unit_html %>% 
        html_element(".contentArea ") %>% 
        html_element("p:nth-child(2)") %>% 
        html_text() %>% 
        str_remove(".*\\: ")
    
      # reqs <- unit_html %>% 
      #   html_element("#contentpadding") %>% 
      #   html_element("div.contentArea") %>% 
      #   html_element("p") %>% 
      #   html_text()
      #requisite hard to extract
      
      overviews <- unit_html %>% 
        html_element("#Overview") %>% 
        html_element(".OverviewInner") %>% 
        html_elements("div") %>% 
        html_text() %>% 
        pluck(2)
      
      outcomes <- unit_html %>% 
        html_elements("#Learningoutcomes .AccordionItem") %>%
        html_text() %>% 
        str_replace("^[0-9]+[.]", "") %>%
        str_replace("keyboard_arrow_down$", "")
      message(glue::glue("{cunit} done!"))
      tibble(!!!c(list(Course = title, 
                       Course_code = code, 
                       Unit_code = cunit,
                       Unit = subject_text,
                       Overview = overviews,
                       Outcomes = list(outcomes)), 
                       reqs_list))
})

data %>% 
  rowwise() %>% 
  mutate(Outcomes = paste(Outcomes, collapse = "| "),
         Prohibition = paste(Prohibition, collapse = ", "),
         Prerequisite = paste(Prerequisite, collapse = ", "),
         Corequisite = paste(Corequisite, collapse = ", ")) %>% 
  mutate(across(c(Prohibition, Prerequisite, Corequisite), 
               ~ifelse(is.na(.x), 
                       "", 
                       str_replace_all(.x, glue::glue("/{year}/units/"), "")))) %>% 
  write_csv(file = "../data/monash-master-datasci.csv")
```