---
title: "Master of Data Science - Swinburne University of Technology"
author: "Rachel Xinrui WANG"
date: "`r Sys.Date()`"
format: 
  html:
    code-fold: false
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(RSelenium)
library(glue)
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      cache.path = "cache/",
                      fig.path = "images/")

```

```{r}
# remDr$close()
# system("taskkill /im java.exe /f", intern=FALSE, ignore.stdout=FALSE)
rD <- rsDriver(browser="firefox", port=4778L, verbose=F)
remDr <- rD[["client"]]

wait_time <- function() Sys.sleep(sample(2:3, 1))

data <- tibble(Course = character(),
               Course_code = character(),
               Course_overview = character(),
               Unit = character(),
               Unit_code = character(),
               Overview = character(),
               #Prerequisite = character(),
               #Corequisite = character(),
               #Prohibition = character(),
               LearningOutcome = character(),
               Requirements = character())

remDr$navigate("https://www.swinburne.edu.au/study/course/Master-of-Data-Science-MA-DATASC/local")
course_html <- read_html(remDr$getPageSource()[[1]])

```


```{r}
tryCatch({
  
  # extract name of the course
    title <- course_html %>% 
      html_element("h1") %>% 
      html_text()
    
  # extract course code
    code <- course_html %>% 
      html_element(".course-meta") %>% 
      html_element(".course-code") %>% 
      html_text()
    
  # extract course overview
    coverview <- course_html %>% 
      html_element("#main-content-area") %>% 
      html_element(".with-margins") %>% 
      #html_elements("p") %>%
      html_text() %>% 
      trimws()
  
    # extract all listed units
    curriculum <- course_html %>% 
      html_element("#course-detail") %>% 
      html_element(".row") %>% 
      html_elements("a") %>% 
      html_attr("href")
  
    for(unit in curriculum) {
      remDr$navigate(unit)
      wait_time()
      unit_html <- read_html(remDr$getPageSource()[[1]])
      
      # unit name
      subject_text <- unit_html %>% 
        html_element("h1") %>% 
        html_text()
      
      # unit code
      cunit <- unit_html %>% 
        html_element(".course-meta") %>% 
        html_element(".course-code") %>% 
        html_text() %>% 
        trimws()
      
      # unit overview and learning outcome
      unitinfo <- unit_html %>% 
        html_element(".main-content") %>% 
        html_element(".section-highlight") %>%
        html_elements(".with-margins") %>%
        html_text() %>% 
        trimws() %>% 
        strsplit("Unit Learning Outcomes")
      
      # unit overview
      overview <- unitinfo[[1]][1]
      
      # unit learning outcome
      lo <- unitinfo[[1]][length(unitinfo[[1]])]
      
      # check if there's any requisite, extract if yes
      req <- unit_html %>% 
        html_element(".main-content") %>% 
        html_elements(".course-info")
      
      if(length(req) > 3){
        reqs <- req[length(req)] %>% 
          html_text() %>% 
          trimws()
      
      }
      
      data <- data %>% 
        bind_rows(tibble(!!!c(list(Course = title, 
                                   Course_code = code, 
                                   Course_overview = coverview,
                                   Unit_code = cunit,
                                   Unit = subject_text,
                                   Overview = overview,
                                   LearningOutcome = lo,
                                   Requirements = reqs)))) %>% 
        mutate(Unit_type = 
                 case_when(row_number()<= 12 ~ "Core",
                           row_number() > 12 ~ "Elective"))
    }
  
}, error = function(x) x
)
```

```{r}
write.csv(data, file = "../data/swb-master-datasci.csv")
```
